version: '2'
services:
  consumptionui-app:
    image: consumptionui
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://consumptionui-postgresql:5432/ConsumptionUI
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  consumptionui-postgresql:
    extends:
      file: postgresql.yml
      service: consumptionui-postgresql
